### ISSUE TITLE
Signs cannot read under $1

### ISSUE THREAD

**Issue by japtic** [TheoKah/CarrotShop#7]
Hi,

So if I setup a sign with 0.01 the plugin will say it will be $1
I believe its for both sell and buy shop.
Possible to fix it so that people can sell or buy things under 1?

thanks in advance!

**Comment by aWitch-Doctor** [comment]
To quote TheoKah from closed issue https://github.com/TheoKah/CarrotShop/issues/6

"About the decimal. This is not something I want to add now. I had problems when I first tried to handle that, and you can achieve similar goal changing the number or items.

Instead of selling 1 item for 0.1, you will sell 10 for 1"

**Comment by TheoKah** [comment]
Yep as aWitch-Doctor said.

I will probably handle that eventually, just not yet as this is not a simple regexp.
Real problem is if I want to handle all possibilities:
- 1.5
- 1,5
- 1,357.24
- ...

There is a lot of subconditions
